### PR TITLE
Update DCAP Linux driver to v1.35

### LINKED ISSUE #2850: Need to update URLs for Intel Linux drivers in the setup scripts
Since Intel has released new SGX and DCAP drivers for Linux, it needs to update the URLs of Intel drivers in the Ansible scripts:
openenclave/scripts/ansible/roles/linux/intel/vars/ubuntu/xenial.yml
openenclave/scripts/ansible/roles/linux/intel/vars/ubuntu/bionic.yml
Otherwise there will be execution problems with the latest Intel DCAP/SGX packages installed by APT.

The latest drivers from Intel are at:
https://download.01.org/intel-sgx/sgx-dcap/1.6/linux/distro/ubuntuServer16.04/sgx_linux_x64_driver_1.32.bin
https://download.01.org/intel-sgx/sgx-dcap/1.6/linux/distro/ubuntuServer18.04/sgx_linux_x64_driver_1.32.bin
https://download.01.org/intel-sgx/sgx-linux/2.9/distro/ubuntu16.04-server/sgx_linux_x64_driver_2.6.0_95eaa6f.bin
https://download.01.org/intel-sgx/sgx-linux/2.9/distro/ubuntu18.04-server/sgx_linux_x64_driver_2.6.0_95eaa6f.bin

### PR DESCRIPTION
**Pull request by rs--**
Due to incompatibilities between the new Azure Linux 5.4 release, and DCAP driver v1.33, an update to DCAP driver v1.35 is required. DCAP driver v1.35 is compatible with the current Azure Linux release on both 16.04 and 18.04.

Ran a successful end-to-end test here: https://oe-jenkins-tf.westeurope.cloudapp.azure.com/job/CI-CD_Infrastructure/job/OpenEnclave-E2E-Testing/242/

Closes #2850

Signed-off-by: Rob Sanchez <rosan@microsoft.com>

### CODE REVIEW

**Comment by BRMcLaren** [comment]
LGTM. For my own education, do we know if this is an Azure Linux kernel only issue? We need to use Azure products for SGX, but wondering where the dependency lies.

**Comment by rs--** [comment]
> LGTM. For my own education, do we know if this is an Azure Linux kernel only issue? We need to use Azure products for SGX, but wondering where the dependency lies.

I'm not quite sure, but it seems to be incompatibilities with the 1.33 driver

```
rosan@rosan-ktest:~/openenclave$ sudo /tmp/sgx_linux_x64_driver.bin
Unpacking Intel SGX Driver ... done.
Verifying the integrity of the install package ... done.
Installing Intel SGX Driver ...
/tmp/sgx-driver-GfcOBd ~/openenclave
install -d /opt/intel/sgxdriver/package
install -d /opt/intel/sgxdriver/scripts
cp -r package/* /opt/intel/sgxdriver/package
install scripts/* /opt/intel/sgxdriver/scripts
~/openenclave
Kernel preparation unnecessary for this kernel.  Skipping...
Building module:
cleaning build area...
'make' KDIR=/lib/modules/5.4.0-1022-azure/build...(bad exit status: 2)
ERROR (dkms apport): binary package for sgx: 1.33 not found
Error! Bad return status for module build on kernel: 5.4.0-1022-azure (x86_64)
Consult /var/lib/dkms/sgx/1.33/build/make.log for more information.

----------- LOG FILE -------------

rosan@rosan-ktest:~/openenclave$ cat /var/lib/dkms/sgx/1.33/build/make.log
DKMS make.log for sgx-1.33 for kernel 5.4.0-1022-azure (x86_64)
Tue Aug 11 21:33:15 UTC 2020
make -C /lib/modules/5.4.0-1022-azure/build M=/var/lib/dkms/sgx/1.33/build CFLAGS_MODULE="-I/var/lib/dkms/sgx/1.33/build -I/var/lib/dkms/sgx/1.33/build/include" modules
make[1]: Entering directory '/usr/src/linux-headers-5.4.0-1022-azure'
  CC [M]  /var/lib/dkms/sgx/1.33/build/encl.o
In file included from ./include/asm-generic/bug.h:5:0,
                 from ./arch/x86/include/asm/bug.h:83,
                 from ./include/linux/bug.h:5,
                 from ./include/linux/mmdebug.h:5,
                 from ./include/linux/mm.h:9,
                 from /var/lib/dkms/sgx/1.33/build/encl.c:5:
/var/lib/dkms/sgx/1.33/build/encl.c: In function ‘sgx_encl_mm_release_deferred’:
./include/linux/kernel.h:994:51: error: ‘struct sgx_encl_mm’ has no member named ‘rcu’
  BUILD_BUG_ON_MSG(!__same_type(*(ptr), ((type *)0)->member) && \
                                                   ^
./include/linux/compiler.h:330:9: note: in definition of macro ‘__compiletime_assert’
   if (!(condition))     \
         ^~~~~~~~~
./include/linux/compiler.h:350:2: note: in expansion of macro ‘_compiletime_assert’
  _compiletime_assert(condition, msg, __compiletime_assert_, __COUNTER__)
  ^~~~~~~~~~~~~~~~~~~
./include/linux/build_bug.h:39:37: note: in expansion of macro ‘compiletime_assert’
 #define BUILD_BUG_ON_MSG(cond, msg) compiletime_assert(!(cond), msg)
                                     ^~~~~~~~~~~~~~~~~~
./include/linux/kernel.h:994:2: note: in expansion of macro ‘BUILD_BUG_ON_MSG’
  BUILD_BUG_ON_MSG(!__same_type(*(ptr), ((type *)0)->member) && \
  ^~~~~~~~~~~~~~~~
./include/linux/kernel.h:994:20: note: in expansion of macro ‘__same_type’
  BUILD_BUG_ON_MSG(!__same_type(*(ptr), ((type *)0)->member) && \
                    ^~~~~~~~~~~
/var/lib/dkms/sgx/1.33/build/encl.c:140:3: note: in expansion of macro ‘container_of’
   container_of(rcu, struct sgx_encl_mm, rcu);
   ^~~~~~~~~~~~
In file included from <command-line>:0:0:
././include/linux/compiler_types.h:129:35: error: ‘struct sgx_encl_mm’ has no member named ‘rcu’
 #define __compiler_offsetof(a, b) __builtin_offsetof(a, b)
                                   ^
./include/linux/stddef.h:17:32: note: in expansion of macro ‘__compiler_offsetof’
 #define offsetof(TYPE, MEMBER) __compiler_offsetof(TYPE, MEMBER)
                                ^~~~~~~~~~~~~~~~~~~
./include/linux/kernel.h:997:21: note: in expansion of macro ‘offsetof’
  ((type *)(__mptr - offsetof(type, member))); })
                     ^~~~~~~~
/var/lib/dkms/sgx/1.33/build/encl.c:140:3: note: in expansion of macro ‘container_of’
   container_of(rcu, struct sgx_encl_mm, rcu);
   ^~~~~~~~~~~~
At top level:
/var/lib/dkms/sgx/1.33/build/encl.c:137:13: warning: ‘sgx_encl_mm_release_deferred’ defined but not used [-Wunused-function]
 static void sgx_encl_mm_release_deferred(struct rcu_head *rcu)
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
scripts/Makefile.build:273: recipe for target '/var/lib/dkms/sgx/1.33/build/encl.o' failed
make[2]: *** [/var/lib/dkms/sgx/1.33/build/encl.o] Error 1
Makefile:1731: recipe for target '/var/lib/dkms/sgx/1.33/build' failed
make[1]: *** [/var/lib/dkms/sgx/1.33/build] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-5.4.0-1022-azure'
Makefile:22: recipe for target 'default' failed
make: *** [default] Error 2
```

**Comment by anakrish** [comment]
Wouldn't this be considered a breaking change in the upstream driver? If so, wouldn't the version be 1.4 ?

**Comment by BRMcLaren** [comment]
@rs-- Mind linking this as a fix? https://github.com/openenclave/openenclave/issues/2850

**Comment by rs--** [comment]
@anakrish  what do you mean by the upstream driver?

**Comment by anakrish** [comment]
@rs-- By upstream I meant Intel. This seems like a breaking change; although I'm not sure if we can do anything differently.

Once this change goes in, does this mean that users must now upgrade their kernel to 5.4 so that OE would continue to work?

**Comment by BRMcLaren** [comment]
@anakrish No, they will not need to. 5.3 will work with 1.35, but 5.4 will not work with 1.33.

Intel is aware of the issue, but I am not sure if this counts as a breaking change. What are your thoughts?

**Comment by rs--** [comment]
@anakrish as a follow up to @BRMcLaren , I tested a few different scenarios with the current kernel, and the 5.4 kernel.


  | Fresh install on current Linux kernel | Fresh install on upcoming Linux Kernel | Upgrading with driver installed
-- | -- | -- | --
DCAP driver v1.33 | Success | Failure | Success
DCAP driver v1.35 | Success | Success | Success

**Comment by BRMcLaren** [comment]
@CodeMonkeyLeet @rs-- I actually tried this update a few days ago, there was an issue on the rhel side: https://github.com/openenclave/openenclave/pull/3304 I never had a chance to look into it in depth though.

**Comment by rs--** [comment]
@CodeMonkeyLeet I've updated the links for Intel's SDK. I figured we can push the docs update to a different PR so a more thorough job can be done.

**Comment by CodeMonkeyLeet** [comment]
@rs-- That's fine, we should just get this in, but can you clean up the related tasks here?
- [ ] File an issue for updating the RHEL setup that Brett ran into in #3304 
- [ ] Close out #3304 as superseded by this PR (the only missing piece is the RHEL update)
- [ ] Close out #2850 as resolved (it was for the previous version of the drivers still)
- [ ] File issues or spin up a new PR for the doc updates.

**Comment by radhikaj** [comment]
Bors r*

**Comment by radhikaj** [comment]
Bors r+
