### ISSUE TITLE
v0.13 causes problems for building app with mbedtls

### ISSUE THREAD

**Issue by praenubilus** [openenclave/openenclave#3787]
We have application using mbedtls-dev lib installed on Ubuntu 18.04. Application builds and works fine with OE v0.12. After upgrading to v0.13, undefined reference errors are prompt when compiling. Below are part of the error info

```bash

transport_utils.o: In function `encode_base64':
/home/userabc/workspaces/app/common/transport_utils.c:133: undefined reference to `mbedtls_base64_encode'
transport_utils.o: In function `print_mbedtls_error_info':
/home/userabc/workspaces/app/common/transport_utils.c:23: undefined reference to `mbedtls_strerror'
/home/userabc/workspaces/app/lib/libskr/lib/libskr.a(SecureKeyRelease.cpp.o): In function `microsoft::mbedtls::Context<mbedtls_pk_context, &mbedtls_pk_init, &mbedtls_pk_free>::Context()':
/home/userabc/workspace/app/external/libskr/library/private/cryptography/mbedtls/context.h:20: undefined reference to `mbedtls_pk_init'
/home/userabc/workspaces/app/lib/libskr/lib/libskr.a(SecureKeyRelease.cpp.o): In function `microsoft::mbedtls::Context<mbedtls_pk_context, &mbedtls_pk_init, &mbedtls_pk_free>::~Context()':
/home/userabc/workspace/app/external/libskr/library/private/cryptography/mbedtls/context.h:25: undefined reference to `mbedtls_pk_free'
/home/userabc/workspaces/app/lib/libskr/lib/libskr.a(SecureKeyRelease.cpp.o): In function `microsoft::mbedtls::Context<mbedtls_mpi, &mbedtls_mpi_init, &mbedtls_mpi_free>::~Context()':
/home/userabc/workspace/app/external/libskr/library/private/cryptography/mbedtls/context.h:25: undefined reference to `mbedtls_mpi_free'
/home/userabc/workspaces/app/lib/libskr/lib/libskr.a(RsaOaepEncryptionTransform.cpp.o): In function `microsoft::mbedtls::mbed_error::mbed_error(int, char const*)':
/home/userabc/workspace/app/external/libskr/library/private/cryptography/mbedtls/error.h:24: undefined reference to `mbedtls_strerror'
/home/userabc/workspaces/app/lib/libskr/lib/libskr.a(RsaOaepEncryptionTransform.cpp.o): In function `microsoft::skr::RsaOaepEncryptionTransform::decrypt(std::__1::vector<unsigned char, std::__1::allocator<unsigned char> > const&)':
/home/userabc/workspace/app/external/libskr/library/src/cryptography/RsaOaepEncryptionTransform.cpp:52: undefined reference to `mbedtls_rsa_set_padding'
/home/userabc/workspace/app/external/libskr/library/src/cryptography/RsaOaepEncryptionTransform.cpp:58: undefined reference to `mbedtls_ctr_drbg_random'
```

**Comment by praenubilus** [comment]
As it turns out there are breaking changes introduced in v0.13 https://github.com/openenclave/openenclave/blob/master/CHANGELOG.md
