### ISSUE TITLE
Does not build with GCC 7.2.0 (Ubuntu 17)

### ISSUE THREAD

**Issue by flxflx** [openenclave/openenclave#93]
When trying to build on a default Ubuntu 17, I am getting the following error:

```
[ 62%] Built target cxxrt-shared
Scanning dependencies of target cxxrt-static
[ 62%] Building CXX object 3rdparty/libcxxrt/libcxxrt/src/CMakeFiles/cxxrt-static.dir/dynamic_cast.cc.o
[ 63%] Building CXX object 3rdparty/libcxxrt/libcxxrt/src/CMakeFiles/cxxrt-static.dir/exception.cc.o
[ 63%] Building CXX object 3rdparty/libcxxrt/libcxxrt/src/CMakeFiles/cxxrt-static.dir/guard.cc.o
[ 63%] Building CXX object 3rdparty/libcxxrt/libcxxrt/src/CMakeFiles/cxxrt-static.dir/stdexcept.cc.o
[ 63%] Building CXX object 3rdparty/libcxxrt/libcxxrt/src/CMakeFiles/cxxrt-static.dir/typeinfo.cc.o
[ 63%] Building CXX object 3rdparty/libcxxrt/libcxxrt/src/CMakeFiles/cxxrt-static.dir/memory.cc.o
/home/felix/openenclave/3rdparty/libcxxrt/libcxxrt/src/memory.cc:159:39: error: ‘std::size_t’ has not been declared
 void operator delete(void * ptr, std::size_t) NOEXCEPT
                                       ^~~~~~
/home/felix/openenclave/3rdparty/libcxxrt/libcxxrt/src/memory.cc:166:41: error: ‘std::size_t’ has not been declared
 void operator delete[](void * ptr, std::size_t) NOEXCEPT
                                         ^~~~~~
3rdparty/libcxxrt/libcxxrt/src/CMakeFiles/cxxrt-static.dir/build.make:182: recipe for target '3rdparty/libcxxrt/libcxxrt/src/CMakeFiles/cxxrt-static.dir/memory.cc.o' failed
make[2]: *** [3rdparty/libcxxrt/libcxxrt/src/CMakeFiles/cxxrt-static.dir/memory.cc.o] Error 1
CMakeFiles/Makefile2:1237: recipe for target '3rdparty/libcxxrt/libcxxrt/src/CMakeFiles/cxxrt-static.dir/all' failed
make[1]: *** [3rdparty/libcxxrt/libcxxrt/src/CMakeFiles/cxxrt-static.dir/all] Error 2
Makefile:162: recipe for target 'all' failed
make: *** [all] Error 2
```

Manually defining size_t in memory.cc helps, but I then get the following linker error later:

```
[ 66%] Linking C executable ../../output/bin/oesign
/usr/bin/ld: ../../output/lib/openenclave/host/liboehost.a(entersim.S.o): relocation R_X86_64_32S against `.text' cannot be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Nonrepresentable section on output
collect2: error: ld returned 1 exit status
tools/oesign/CMakeFiles/oesign.dir/build.make:97: recipe for target 'output/bin/oesign' failed
make[2]: *** [output/bin/oesign] Error 1
CMakeFiles/Makefile2:9590: recipe for target 'tools/oesign/CMakeFiles/oesign.dir/all' failed
make[1]: *** [tools/oesign/CMakeFiles/oesign.dir/all] Error 2
Makefile:162: recipe for target 'all' failed
make: *** [all] Error 2
```
